#cloud-config
package_update: true
package_upgrade: true

packages:
  - docker.io
  - docker-compose
  - fail2ban
  - chrony
  - curl
  - wget
  - git

users:
  - name: deploy
    groups: docker
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - ${ssh_public_key}

runcmd:
  - usermod -aG docker deploy
  - systemctl enable fail2ban
  - systemctl start fail2ban
  - systemctl enable chrony
  - systemctl start chrony
  - systemctl enable docker
  - systemctl start docker

final_message: "RobinCore configuration applied to existing server"
